### PR TITLE
Removed extraneous `or`

### PR DESCRIPTION
**Pull request by blakeembrey**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
@blakeembrey could you add your name to the `contributors` array in package.json please? also on the readme if you want. I can do both if you're strapped for time. 

thanks!

**Comment by blakeembrey** [comment]
@jonschlinkert No `package.json` on this project 😄 I can add it to the README, but if I'm going to be marked as a contributor hopefully I can make some more worthwhile contributions.

**Comment by jonschlinkert** [comment]
haha, well I guess my head is in node.js space. thank you! 

> I'm going to be marked as a contributor hopefully I can make some more worthwhile contributions.

that would be awesome, but no expectations on my end, I know you're busy!

**Pull request merged**
